spring.application.name=construplaza

# ===============================
# DATASOURCE (CLEVER CLOUD)
# ===============================
spring.datasource.url=jdbc:mysql://bjmg9pxkmau7igfaao2d-mysql.services.clever-cloud.com:3306/bjmg9pxkmau7igfaao2d?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=uorzqket5pp5qpu5
spring.datasource.password=tIoJe0uGnZKxQfWlf4QL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}